In [2]:
import numpy as np 

a = np.array([1,2,3,4])

print(a)

[1 2 3 4]


In [14]:
import time 

a = np.random.rand(1000000)

b = np.random.rand(1000000)

tic = time.time()

c = np.dot(a,b)

toc = time.time()

print("vectorised version:",  str(1000*(toc-tic)) + "ms")

vectorised version: 0.0ms


In [15]:
%%timeit
a = np.random.rand(1000000)

b = np.random.rand(1000000)

c = np.dot(a,b)



13.2 ms ± 665 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
c = 0 
tic = time.time()

for i in range(1000000):
    c += a[i] * b[i]

toc = time.time()

print(str(1000*(toc - tic)), "ms")

243.70884895324707 ms


Logistic regression derivatives

below is the non-vectorised version. let's see how can we change it later on

In [ ]:
m  = 10
z = np.zeros(10)
w = np.zeros(2)
x = np.zeros(10)
a = np.zeros(10)
y = np.zeros(10)
dz = np.zeros(10)


def activation_func(z):
    pass

# Initialise 
j, dw_1, dw_2, db = 0,0,0,0

for i in range(1,m+1):
    z[i] = w.T*x[i] + b
    a[i] = activation_func(z[i])
    # cost function
    j += -( y[i]* np.log(a[i]) + (1-y[i]) *np.log(1-a[i]) )

    dz[i] = a[i] - y[i]
    
    #updates (suppose to be a for loop)
    dw_1 += x_1[i] * dz[i]

    dw_2 += x_2[i] * dz[i]

    db += dz[i]

# average it 
j, dw_1, dw_2, db = j/m, dw_1/m, dw_2/m, db/m




In [ ]:
m  = 10
z = np.zeros(10)
w = np.zeros(2)
x = np.zeros(10)
a = np.zeros(10)
y = np.zeros(10)
dz = np.zeros(10)
n_x = 10


def activation_func(z):
    pass

# Initialise 
j, db = 0,0

dw = np.zeros((n_x, 1))

for i in range(1,m+1):
    z[i] = w.T*x[i] + b
    a[i] = activation_func(z[i])
    # cost function
    j += -( y[i]* np.log(a[i]) + (1-y[i]) *np.log(1-a[i]) )

    dz[i] = a[i] - y[i]
    
    #updates (suppose to be a for loop)
    dw += x[i] * dz[i]

    db += dz[i]

# average it 
j, db = j/m, db/m
dw /= m


Proper vectorised solution below 

In [ ]:
#learning rate
alph = 0.1
n_x = 10
m = 10 
X = np.ones(n_x,m)
Y = np.ones(1,m)


# Iterations 
for iter in range(100):

    # Forward Pass 
    Z = np.dot(W.T, X) + b
    A = activation_func(Z)

    # Back propagation
    dZ = A - Y   # dZ has (1,m) dimensions
    dw = (X/m) * dZ.T # (n_x,m) * (m,1)
    db = np.sum(dZ)/m 

    # Updates
    w = w - alph * dw
    b = b - alph * db
 

Practice broadcasting 


In [ ]:
"""
            Apples   Beef    Eggs   Potatoes 
Carbs
Protein
Fat 

"""

A = np.array(
    [[56.0, 0.0, 4.4, 68.0],
    [1.2, 104.0, 52.0, 8.0],
    [1.8, 135.0, 99.0, 0.9]]
)

A.shape

(3, 4)

axis = 0 collapses the rows together 

In [5]:
cal = A.sum(axis=0)

cal 

array([ 59. , 239. , 155.4,  76.9])

code below is broadcasting where we are dividing a (3,4) matrix by (1,4) matrix 

In [ ]:
percentage = A/(cal.reshape(1,4)) * 100

percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])